#
# Virtuelle Maschine für fm-ProductNode 2.0
#
# Autor: Franz Muehlbauer, info@fm-productnode.de; 2017
# Lizenz: MIT
#

os							= "ubuntu/xenial64" # Ubuntu 16.04
server_memory		= "8192"		# MB - abhängig von der Hardware und der Größe der zu verarbeitenden Produktkataloge
server_swap			= "8192" 	# Options: false | int (MB) - Daumenregel: 1 - 2 mal server_memory

Vagrant.configure("2") do |config|
  config.vm.box = os

  config.vm.provider :virtualbox do |vb|
    vb.cpus = "1"
    vb.memory = server_memory
  end
  
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

  config.vm.provision "shell", path: "fmpn2_0.sh"

end
